include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    always_use_package_imports: true
    annotate_overrides: true
    avoid_final_parameters: true
    avoid_unnecessary_containers: true
    avoid_unused_constructor_parameters: true
    camel_case_types: true
    comment_references: true
    constant_identifier_names: true
    depend_on_referenced_packages: true
    document_ignores: true
    empty_constructor_bodies: true
    empty_statements: true
    enable_null_safety: true
    eol_at_end_of_file: true
    flutter_style_todos: true
    file_names: true
    implementation_imports: true
    library_names: true
    no_duplicate_case_values: true
    no_runtimeType_toString: true