name: E-Waste Mobile Application CI/CD Pipeline

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  checkout:
    runs-on: ${{matrix.os}}
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      
      - name: Checkout Repository
        uses: actions/checkout@v4

  build:
    needs: checkout
    runs-on: ${{matrix.os}}
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest]
        channel: [stable]
    steps:

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: ${{matrix.channel}}
      - run: flutter --version

      - name: Setup Dart Language
        uses: dart-lang/setup-dart@v1
        
      - name: Install Dependencies
        run: flutter pub get
        
  test:
    needs: build
    runs-on: ${{matrix.os}}
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
         
      - name: Dart Code Format
        run: dart format .

      - name: Verify Dart Formatting
        run: dart format --output=none --set-exit-if-changed.
        
      - name: Analyze Project Source
        run: flutter analyze
        
      # - name: Run Tests
      #   run: flutter test